# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  config.vm.define "machine_1" do |vm1|
    vm1.vm.box = "shekeriev/debian-12"
    vm1.vm.hostname = "machine-1"
    vm1.vm.network "private_network", ip: "192.168.200.100"
    vm1.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
    vm1.vm.disk :disk, size: "5GB", name: "extra_storage_1"
    vm1.vm.disk :disk, size: "5GB", name: "extra_storage_2"
    vm1.vm.disk :disk, size: "5GB", name: "extra_storage_3"
    vm1.vm.disk :disk, size: "5GB", name: "extra_storage_4"
  end
end
