# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  config.vm.define "machine_1" do |vm1|
    vm1.vm.box = "shekeriev/debian-12"
    vm1.vm.hostname = "str"
    vm1.vm.network "private_network", ip: "192.168.200.10"
    vm1.vm.disk :disk, size: "1GB", name: "extra_storage_1"
    vm1.vm.disk :disk, size: "1GB", name: "extra_storage_2"
    vm1.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "machine_2" do |vm2|
    vm2.vm.box = "shekeriev/debian-12"
    vm2.vm.hostname = "cnt"
    vm2.vm.network "private_network", ip: "192.168.200.20"
    vm2.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "machine_3" do |vm3|
    vm3.vm.box = "shekeriev/debian-12"
    vm3.vm.hostname = "lba"
    vm3.vm.network "private_network", ip: "192.168.200.30" 
    vm3.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "machine_4" do |vm3|
    vm3.vm.box = "shekeriev/debian-12"
    vm3.vm.hostname = "wba"
    vm3.vm.network "private_network", ip: "192.168.200.40" 
    vm3.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "machine_5" do |vm3|
    vm3.vm.box = "shekeriev/debian-12"
    vm3.vm.hostname = "wbb"
    vm3.vm.network "private_network", ip: "192.168.200.50" 
    vm3.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "machine_6" do |vm3|
    vm3.vm.box = "shekeriev/debian-12"
    vm3.vm.hostname = "mon"
    vm3.vm.network "private_network", ip: "192.168.200.60" 
    vm3.vm.network "forwarded_port", guest: 80, host: 8888
    vm3.vm.provider :virtualbox do |vb|
      vb.memory = 2048
    end
  end
end


